<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LenovoPC" ignored="0" name="test1" tests="4" failures="2" timestamp="21 十月 2017 02:58:04 GMT" time="0.124" errors="0">
  <testcase name="f1" time="0.023" classname="com.liangxin.CalcTest"/>
  <testcase name="f2" time="0.003" classname="com.liangxin.CalcTest"/>
  <testcase name="f3" time="0.021" classname="com.liangxin.CalcTest">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [1]
	at com.liangxin.CalcTest.f3(CalcTest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f3 -->
  <testcase name="f4" time="0.009" classname="com.liangxin.CalcTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [5]
	at com.liangxin.CalcTest.f4(CalcTest.java:24)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f4 -->
</testsuite> <!-- test1 -->
